#

umask 0077

if [ $EMACS ]; then 
  echo Hello Emacs
fi
export PS1='\n$(/usr/local/bin/Z)\n\u@\h§\w§\n> '
export PS2='>'

PATH=~/tools/bin:$PATH

PS_FORMAT=user:15,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
export PS_FORMAT

EDITOR=emacs
export EDITOR


