#!/bin/bash
# must have commands rsync and user-stem
# user-stem is in the system repo
#
# wish we could set the uids and gids so that backups would restore properly on other systems but it is too much trouble
# to do in a shell script.  Perhaps in the python code for the actual release.
set -x

subu=$1
stem=$2

if [ ! -x "/usr/local/bin/user-stem" ]; then
   echo "no /usr/local/bin/user-stem program found (it is in the system repo)"
   exit 1
fi

if [ -z "$subu" ]; then
   echo "no subuser name supplied"
   exit 1
fi

# stem includes all characters up to the first '-' 
if [ -z "$stem" ]; then
  stem=$(/usr/local/bin/user-stem)
fi

subu_username="$stem-$subu"
admin_username="$stem-admin"

subu_home="/home/$stem"
subu_dir="$subu_home/$subu"
subu_user="$subu_dir"/user

admin_home="/home/$stem/admin"
subu_initial_files="$admin_home"/user/library/subu_initial_files

sudo useradd --badname --home-dir "$subu_dir"  "$subu_username"
sudo usermod -aG "$subu_username" "$admin_username"

if [[ ! -d "$subu_user" ]]; then
    sudo mkdir "$subu_user"
    sudo chown "$subu_username":"$subu_username" "$subu_user"
fi

subu_initialize "$subu" "$stem"



