#!/bin/bash
#

# to make audio work will need to do this:
#    > sudo dnf install pulseaudio-utils
#    > pactl load-module module-native-protocol-tcp
# To load a specific module to the PA server, you add it to /etc/pulse/default.pa:
# I created the file because it was not there... 

#set -x

subu=$1
stem=$2


if [ ! -x "/usr/local/bin/user-stem" ]; then
   echo "no /usr/local/bin/user-stem program found (it is in the system repo)"
   exit 1
fi

if [ -z "$subu" ]; then
   echo "no subuser name supplied"
   exit 1
fi

machine="$(hostname)"
xkey=$(xauth list | grep "$machine" | head -1 | awk '{print $3}')

if [ -z "$xkey" ]; then
   echo "xauth key not found"
   exit 1
fi

# stem includes all characters up to the first '-' 
if [ -z "$stem" ]; then
  stem=$(/usr/local/bin/user-stem)
fi

subu_username="$stem-$subu"
subu_user_directory=/home/"$stem"/"$subu"/user
bashrc="$subu_user_directory/.bashrc"
xauthority="$subu_user_directory/.Xauthority"

read -r -d '' script0 <<-EOF
    cd "$subu_user_directory" \
    ;export DISPLAY=$DISPLAY \
    ;export NO_AT_BRIDGE=1 \
    ;export PULSE_SERVER=localhost \
    ;touch "$xauthority" \
    ;xauth add "$DISPLAY" . "$xkey" \
    ;gnome-terminal --title="$subu"
EOF


sudo su  -l "$subu_username" -c "$script0"

#just hangs
#sudo -u  "$subu_username" sh -c "$script0"

#set +x
