#

umask 0077

if [ $INSIDE_EMACS ]; then 
  echo Hello Emacs
fi
export PS1='\n$(/usr/local/bin/Z)\n\u@\h§\w§\n> '
export PS2='>>'
PATH=~/bin:$PATH

#temporarily while active in subu code development
export PROJECT_SUBU=~/subu
PATH="$PROJECT_SUBU"/tool/bin:$PATH

export PS_FORMAT=user:15,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command

export EDITOR=emacs


