#!/bin/python

from Xlib import X, display, error, Xatom, Xutil
import sys

def get_xkey():
    d = display.Display()
    window = d.get_input_focus().focus
    xauth = d.get_authorization_data()
    if xauth is not None:
        return xauth.string
    else:
        return None

xkey = get_xkey()
if xkey is None:
    sys.stderr.write("subu:: xauth key not found\n")
    sys.exit(1)
else:
    print(xkey)
