server:
  username: "unbound"
  chroot: ""
  directory: "/etc/unbound"
  do-daemonize: no
  interface: 127.0.0.1@5302
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  qname-minimisation: yes
  prefetch: yes
  outgoing-interface: 10.8.0.2

forward-zone:
  name: "."
  forward-addr: 1.1.1.1
  forward-addr: 1.0.0.1
