#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")
# remove all files in the release directory
set -e

script_name=$(basename ${BASH_SOURCE[0]})
if [ -z "$REPO_HOME" ]; then
  echo "$script_name:: REPO_HOME is not set."
  exit 1
fi

set -x
cd "$REPO_HOME"
rm -rf release/*
set +x

echo "$script_name done."

