#!/usr/bin/env bash

script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards
  env_must_be="developer/tool/env"
  error=false
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    error=true
  fi
  if $error; then exit 1; fi

# remove files

  cd "$REPO_HOME"/developer/
  set -x
  make dist-clean
  cd mockup/subu_server_home
  rm server hello socket 
  set +x

echo "$(script_fn) done."
