#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool/env"
  error=false
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    error=true
  fi
  if $error; then exit 1; fi

set -e
cd ${REPO_HOME}/developer
cp amd64/* mockup/subu_server_home

