#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="tester/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

echo "Compiling files..."

  set -x
  cd $REPO_HOME/tester
  javac -g -d scratchpad javac/*.java
  jar cf jvm/Test_"$PROJECT".jar -C scratchpad .
  set +x 

echo "Creating shell wrappers..."
  mkdir -p shell
  # wrapper is a space separated list
  wrapper=$(shell_wrapper_list)
  for file in $wrapper;do
    cat > shell/$file << EOL
#!/bin/env bash
java $file
EOL
    chmod +x shell/$file
  done

echo "$(script_fp) done."
