[Interface]
PrivateKey = ACd0vEyoZejb+WkXL1LcheHAYm2oRBbw52dJB5+tmUQ=
Table = off
# ListenPort = 51820

[Peer]
PublicKey = h8ZYEEVMForvv9p5Wx+9+eZ87t692hTN7sks5Noedw8=
AllowedIPs = 0.0.0.0/0
Endpoint = 35.194.71.194:443
PersistentKeepalive = 25
