[Interface]
PrivateKey = 0OUqldVHE0GSUM2XUw4o9kgc/OR6smcwED6Wk1HJgGQ=
Table = off
# ListenPort = 51820

[Peer]
PublicKey = pcbDlC1ZVoBYaN83/zAsvIvhgw0iQOL1YZKX5hcAqno=
AllowedIPs = 0.0.0.0/0
Endpoint = 66.248.243.113:51820
PersistentKeepalive = 25
